productized/logic/build-quarkus-app.sh
- Adds the org.kie.kogito:kogito-addons-quarkus-jobs-knative-eventing extension to the build-quakurs-app.sh as a follow-up work from kie-kogito-images-1735
<details>
<summary>
</summary>
- <b>Prod tests</b>  
Please add comment: <b>Jenkins (re)run [prod|Prod|PROD]</b>
</details>
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name …
=> kie-kogito-images-1735: Add the kogito-addons-quarkus-jobs-knative-eventing addon to the swf-builder images

modules/prod/kogito-data-index-ephemeral/added/kogito-app-launch.sh, modules/prod/kogito-data-index-ephemeral/configure, modules/prod/kogito-data-index-ephemeral/module.yaml, modules/prod/kogito-maven/3.9.x-prod/module.yaml, modules/prod/kogito-swf-builder-runtime/configure.sh, modules/prod/kogito-swf-builder-runtime/module.yaml, modules/prod/kogito-swf-devmode-runtime/configure.sh, modules/prod/kogito-swf-devmode-runtime/module.yaml, prod-logic-data-index-ephemeral-rhel8-image.yaml, prod-logic-swf-builder-rhel8-image.yaml, prod-logic-swf-devmode-rhel8-image.yaml
<details>
<summary>
</summary>
- <b>Prod tests</b>  
Please add comment: <b>Jenkins (re)run [prod|Prod|PROD]</b>
</details>
<details>
<summary>
</summary>
> **NOTE**: …
=> Recreate cekit descriptors and prod modules removed from upstream

productized/logic/build-quarkus-app.sh, productized/logic/pom.xml
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> upgrade Quarkus to 3.2.9.Final in productized scripts

modules/kogito-dynamic-resources/added/container-limits
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> Sync main branch with Apache main branch

modules/kogito-swf/devmode/runtime/common/added/run-app-devmode.sh, modules/kogito-swf/devmode/runtime/community/module.yaml
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> SRVLOGIC-231: Disable question about collecting Quarkus analytics

modules/prod/kogito-swf-devmode-runtime/module.yaml
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> [9.99.x-prod] [SRVLOGIC-231] Disable question about collecting Quarkus analytics in prod devmode imag

productized/logic/build-quarkus-app.sh
PR for midstream main will follow soon.
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main …
=> [9.99.x-prod][SRVLOGIC-235] move maven plugins to plugin management and use go-offline option to make sure all deps are downloaded

modules/kogito-dynamic-resources/added/container-limits
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> [1.13.x-next] fix bats tests

modules/kogito-dynamic-resources/added/container-limits
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> [1.13.x-blue-next] fix bats tests

productized/logic/build-quarkus-app.sh
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> [SRVLOGIC-235] move maven plugins to plugin management and use go-offline option to make sure all deps are downloaded

modules/prod/kogito-swf-devmode-runtime/module.yaml
… 
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> [SRVLOGIC-231] Disable question about collecting Quarkus analytics in prod devmode image

productized/logic/build-quarkus-app.sh, productized/logic/pom.xml
…
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> build-quarkus-app.sh: update extensions names based on last changes in kogito projects

modules/prod/kogito-data-index-postgresql/added/kogito-app-launch.sh, modules/prod/kogito-data-index-postgresql/configure, modules/prod/kogito-data-index-postgresql/module.yaml, modules/prod/kogito-jobs-service-ephemeral/added/kogito-app-launch.sh, modules/prod/kogito-jobs-service-ephemeral/configure, modules/prod/kogito-jobs-service-ephemeral/module.yaml, modules/prod/kogito-jobs-service-postgresql/added/kogito-app-launch.sh, modules/prod/kogito-jobs-service-postgresql/configure, modules/prod/kogito-jobs-service-postgresql/module.yaml, modules/prod/kogito-swf-builder-runtime/module.yaml, modules/prod/kogito-swf-devmode-runtime/module.yaml, openshift-serverless-logic-imagestream.yaml, prod-logic-data-index-ephemeral-rhel8-image.yaml, prod-logic-data-index-postgresql-rhel8-image.yaml, prod-logic-jobs-service-ephemeral-rhel8-image.yaml, prod-logic-jobs-service-postgresql-rhel8-image.yaml, prod-logic-swf-builder-rhel8-image.yaml, prod-logic-swf-devmode-rhel8-image.yaml
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> [SRVLOGIC-267] Create cekit descriptors for Data Index PostgreSQL and Jobs Service images

productized/logic/build-quarkus-app.sh
This is required after midstream main branches sync with upstream/main done as part of PRs linked on https://github.com/kiegroup/drools/pull/39
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change …
=> build-quarkus-app.sh: update extensions names based on last changes in kogito projects (part 2)

productized/logic/build-quarkus-app.sh
This is required by Parodos because we are doing an internal release and Kogito artifacts will not be available on MRRC
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a …
=> [9.99.x-prod] add kogito-addons-quarkus-jobs-knative-eventing and kogito-addons-persistence-jdbc extensions to builder and devmode images

modules/kogito-dynamic-resources/added/container-limits
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> [1.13.x-blue] fix bats tests

bamoe-kogito-builder-rhel8-overrides.yaml, bamoe-kogito-imagestream.yaml, bamoe-kogito-runtime-jvm-rhel8-overrides.yaml, bamoe-kogito-runtime-native-rhel8-overrides.yaml, modules/bamoe-kogito-profile/module.yaml
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> [1.13.x-blue] Prepare BAMOE Kogito 8.0.5

prod-logic-swf-builder-rhel8-image.yaml, prod-logic-swf-devmode-rhel8-image.yaml, productized/logic/build-quarkus-app.sh, productized/logic/pom.xml
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> update Quarkus to 3.8.4 in prod images

modules/prod/kogito-data-index-ephemeral/module.yaml, modules/prod/kogito-data-index-postgresql/module.yaml, modules/prod/kogito-image-dependencies/module.yaml, modules/prod/kogito-jobs-service-ephemeral/module.yaml, modules/prod/kogito-jobs-service-postgresql/module.yaml, modules/prod/kogito-pkg-update/module.yaml, modules/prod/kogito-swf-builder-runtime/module.yaml, modules/prod/kogito-swf-devmode-runtime/module.yaml, openshift-serverless-logic-imagestream.yaml, prod-logic-data-index-ephemeral-rhel8-image.yaml, prod-logic-data-index-postgresql-rhel8-image.yaml, prod-logic-jobs-service-ephemeral-rhel8-image.yaml, prod-logic-jobs-service-postgresql-rhel8-image.yaml, prod-logic-swf-builder-rhel8-image.yaml, prod-logic-swf-devmode-rhel8-image.yaml
Related PRs:
- https://github.com/kiegroup/kogito-images/pull/39
- https://github.com/kiegroup/kogito-images/pull/40
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> [9.100.x-prod] set prod images version to 1.33

tests/features/data-index/kogito-data-index-ephemeral.feature, tests/features/data-index/kogito-data-index-postgresql.feature, tests/features/jobs-service/kogito-jobs-service-all-in-one.feature, tests/features/jobs-service/kogito-jobs-service-ephemeral.feature, tests/features/jobs-service/kogito-jobs-service-postgresql.feature
https://issues.redhat.com/browse/SRVLOGIC-232
=> [9.100.x-prod] Fix behave tests expectin incorrect value in test

tests/features/jobs-service/kogito-jobs-service-all-in-one.feature, tests/features/jobs-service/kogito-jobs-service-ephemeral.feature, tests/features/jobs-service/kogito-jobs-service-postgresql.feature
made a mistake, this fixes it and should be the last piece to have images green on our side
=> [9.100.x-prod] Fix images tests expecting job-service instead of jobS-service

modules/prod/kogito-maven/configure, modules/prod/kogito-maven/maven/settings.xml, modules/prod/kogito-maven/module.yaml, prod-logic-swf-builder-rhel8-image.yaml, prod-logic-swf-devmode-rhel8-image.yaml
Issue link: https://issues.redhat.com/browse/SRVLOGIC-311
In this PR, we add a new custom module to override `settings.xml` file to the default Maven installation.
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., …
=> [SRVLOGIC-311] - Add Red Hat repository to Maven installation

modules/prod/kogito-data-index-ephemeral/module.yaml, modules/prod/kogito-data-index-postgresql/module.yaml, modules/prod/kogito-image-dependencies/module.yaml, modules/prod/kogito-jobs-service-ephemeral/module.yaml, modules/prod/kogito-jobs-service-postgresql/module.yaml, modules/prod/kogito-pkg-update/module.yaml, modules/prod/kogito-swf-builder-runtime/module.yaml, modules/prod/kogito-swf-devmode-runtime/module.yaml, openshift-serverless-logic-imagestream.yaml, prod-logic-data-index-ephemeral-rhel8-image.yaml, prod-logic-data-index-postgresql-rhel8-image.yaml, prod-logic-jobs-service-ephemeral-rhel8-image.yaml, prod-logic-jobs-service-postgresql-rhel8-image.yaml, prod-logic-swf-builder-rhel8-image.yaml, prod-logic-swf-devmode-rhel8-image.yaml
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary> …
=> set prod images version to 1.34
